functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []
redirects = []

[functions]

  [functions."*"]

[build]
  functions = "functions"   # folder where your app.js lives
  publish = "."  

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]